# -*- coding: utf-8 -*-
"""TUGAS BESAR PIK DIRMA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPo0J6gIrB5GBDD3n4DrNvTw4Fdq_fl3
"""

import json
import os
import random
from datetime import datetime

SOAL_FILE = "soal.json"
SKOR_FILE = "skor.json"
JAWABAN_FILE = "jawaban.json"

#FUNGSI BANTU
def load_data(file, default):
    if not os.path.exists(file):
        save_data(file, default)
        return default
    try:
        with open(file, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        save_data(file, default)
        return default


def save_data(file, data):
    with open(file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)



DEFAULT_SOAL = [
    {
        "pertanyaan": "Jika 2x - 3 = 13, berapakah nilai x?",
        "pilihan": ["5", "7", "8", "6", "4"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Hasil dari limit lim(x→∞) (3x² + 2x)/(x² - 5) adalah?",
        "pilihan": ["3", "0", "Tak hingga", "1", "2"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "Dalam fisika, besaran turunan berikut yang benar adalah?",
        "pilihan": ["Kecepatan = m/s", "Usaha = m/s²", "Gaya = kg·m²", "Daya = kg/s", "Tekanan = kg"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "Panjang sisi miring segitiga siku-siku dengan alas 6 dan tinggi 8 adalah?",
        "pilihan": ["8", "12", "10", "14", "6"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Jika matriks A berordo 2×2, maka determinannya diperoleh dari?",
        "pilihan": ["(ad + bc)", "ab - cd", "ad - bc", "a + d", "ac + bd"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Bilangan prima terbesar di bawah 50 adalah?",
        "pilihan": ["43", "47", "49", "41", "37"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Rumus umum suku ke-n aritmatika adalah?",
        "pilihan": ["a + (n-1)b", "ab(n-1)", "a/b + n", "a(n-1) + b", "a + bn"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "Planet yang memiliki rotasi paling lambat adalah?",
        "pilihan": ["Bumi", "Mars", "Venus", "Saturnus", "Neptunus"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Rumus energi kinetik adalah?",
        "pilihan": ["mgh", "½mv²", "mv", "½gt²", "F×s"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Pencipta bahasa pemrograman Python adalah?",
        "pilihan": ["Linus Torvalds", "James Gosling", "Guido van Rossum", "Brendan Eich", "Dennis Ritchie"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Hasil dari integral ∫ 2x dx adalah?",
        "pilihan": ["2x² + C", "x² + C", "x²/2 + C", "4x + C", "x + C"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Gaya gesek dipengaruhi oleh?",
        "pilihan": ["Kecepatan benda", "Jenis permukaan", "Waktu gesekan", "Suhu", "Volume benda"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Penyebab utama terjadinya gerhana bulan adalah?",
        "pilihan": ["Bulan berada di antara Matahari dan Bumi", "Bumi berada di antara Matahari dan Bulan", "Rotasi Bulan berhenti", "Orbit Bulan membesar", "Orbit Bumi mengecil"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Jika v = 20 m/s dan t = 8 s, jarak tempuh untuk gerak lurus beraturan adalah?",
        "pilihan": ["120 m", "100 m", "140 m", "160 m", "180 m"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "Satuan SI untuk gaya adalah?",
        "pilihan": ["Joule", "Watt", "Newton", "Pascal", "Ampere"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Hasil dari 12P3 adalah?",
        "pilihan": ["1188", "1320", "950", "1728", "720"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Gas yang paling banyak di atmosfer Bumi adalah?",
        "pilihan": ["Oksigen", "Hidrogen", "Nitrogen", "Karbon Dioksida", "Helium"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "Pembentukan bayangan nyata pada lensa cembung terjadi ketika?",
        "pilihan": ["Objek di antara F dan lensa", "Objek di antara 2F dan F", "Objek di F", "Objek di 2F", "Objek tepat di belakang lensa"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "Hasil akhir reaksi fotosintesis adalah?",
        "pilihan": ["CO₂ dan air", "Oksigen dan glukosa", "Cahaya dan energi", "Kalori", "Nitrogen"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "Alat ukur kuat arus listrik adalah?",
        "pilihan": ["Voltmeter", "Barometer", "Ammeter", "Ohmmeter", "Manometer"],
        "jawaban_index": 2
    }
]


# STREAMLIT

def coba_jalankan_streamlit():
    try:
        import streamlit as st
        import matplotlib.pyplot as plt

# FUNGSU BAR MENU MUNCUL
        st.set_page_config(page_title="Aplikasi Quiz", page_icon="📘", layout="wide")

        st.title("📘 Aplikasi Quiz Sederhana")

# BAR MENU
        menu = st.sidebar.radio(
            "Pilih Menu:",
            ["Mulai Quiz", "Tambah Soal", "Riwayat Nilai", "Grafik Nilai", "Keluar"]
        )

        daftar_soal = load_data(SOAL_FILE, DEFAULT_SOAL)
        skor_data = load_data(SKOR_FILE, [])
        jawaban_data = load_data(JAWABAN_FILE, {})

# MENU MULAI QUIZ
        if menu == "Mulai Quiz":
            st.header("📝 Mulai Quiz")

            if "nomor" not in st.session_state:
                st.session_state.nomor = 0
                st.session_state.jawaban_user = []
                st.session_state.skor = 0

            nomor = st.session_state.nomor

            if nomor < len(daftar_soal):
                soal = daftar_soal[nomor]
                st.write(f"Soal ke-{nomor + 1}: **{soal['pertanyaan']}**")

                pilihan = soal["pilihan"]
                jawaban = st.radio("Pilih jawaban:", pilihan, key=f"soal_{nomor}")

                if st.button("Kirim Jawaban"):
                    index_jawaban = pilihan.index(jawaban)
                    benar = (index_jawaban == soal["jawaban_index"])

                    if benar:
                        st.session_state.skor += 5

                    st.session_state.jawaban_user.append(index_jawaban)
                    st.session_state.nomor += 1
                    st.rerun()
            else:
                st.success(f"Quiz selesai! Skor Anda: {st.session_state.skor}")

                skor_data.append({
                    "waktu": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "skor": st.session_state.skor
                })
                save_data(SKOR_FILE, skor_data)

                st.session_state.clear()

# MENU TAMBAH SOAL
        elif menu == "Tambah Soal":
            st.header("➕ Tambah Soal")
            pertanyaan = st.text_area("Tulis Pertanyaan:")
            opsi = [st.text_input(f"Pilihan {i+1}:") for i in range(5)]
            jawaban_benar = st.selectbox("Pilih jawaban benar:", list(range(1, 6)))

            if st.button("Simpan Soal"):
                daftar_soal.append({
                    "pertanyaan": pertanyaan,
                    "pilihan": opsi,
                    "jawaban_index": jawaban_benar - 1
                })
                save_data(SOAL_FILE, daftar_soal)
                st.success("Soal berhasil disimpan!")

# MENU RIWAYAT NILAI
        elif menu == "Riwayat Nilai":
            st.header("📜 Riwayat Nilai")
            if skor_data:
                for item in skor_data:
                    st.write(f"📅 {item['waktu']} — 🔢 Skor: {item['skor']}")
            else:
                st.info("Belum ada data skor.")

# MENU GRAFIK NILAI
        elif menu == "Grafik Nilai":
            st.header("📊 Grafik Nilai")

            if skor_data:
                plt.plot([i["skor"] for i in skor_data], marker="o")
                plt.title("Perkembangan Skor")
                plt.xlabel("Percobaan Ke-")
                plt.ylabel("Skor")
                st.pyplot(plt)
            else:
                st.info("Belum ada skor untuk ditampilkan.")

# MENU KELUAR
        elif menu == "Keluar":
            st.header("🚪 Keluar")
            st.warning("Anda telah keluar dari aplikasi.")
            st.info("Tutup tab ini, atau pilih menu lain untuk kembali.")
            st.session_state.clear()

        return True

    except ImportError:
        return False

# MODE TERMINAL (jika streamlit tidak tersedia)


def mode_terminal():
    print("=MODE TERMINAL =")
    print("Jalankan dengan Streamlit untuk tampilan lengkap.")
    print("Perintah: streamlit run app.py")


if __name__ == "__main__":
    if not coba_jalankan_streamlit():
        mode_terminal()